#!/usr/bin/lua

require "posix"
local source = debug.getinfo(1).source
local dir = string.match(source, "@(.*)/[^/]*")
if dir then
        local link = posix.readlink(source:match("@(.*)"))
        if link then
                source = dir .. '/' .. link
                dir = string.match(source, "(.*)/[^/]*")
        end
end
if dir then
        package.path = dir .. '/?.lua;' .. package.path
end

local lpeg = require 'lpeg'
local locale = lpeg.locale();
local P, R, S, C = lpeg.P, lpeg.R, lpeg.S
local C, Cc, Ct, Cg = lpeg.C, lpeg.Cc, lpeg.Ct, lpeg.Cg

local DP = require 'dcpu16.parser'
require 'dcpu16.util'

-- lexer

local lexer = {
        finalize = function(self)
                os.exit(0)
        end,
        dump = function(self, file)
                os.exit(0)
        end,
        output = function(self, file)
                os.exit(0)
        end,
}

local lex_actions = {
        comment  = function(...) print('COMMENT', ...) end,
        literal  = function(...) print('LITERAL', ...) end,
        comma    = function(...) print('COMMA', ...) end,
        gop      = function(...) print('GOP', ...) end,
        sop      = function(...) print('SOP', ...) end,
        greg     = function(...) print('GREG', ...) end,
        sreg     = function(...) print('SREG', ...) end,
        mref     = function(...) print('MREF', ...) end,
        variable = function(...) print('VAR', ...) end,
        label    = function(...) print('LABEL', ...) end
}

lexer.matcher = ( DP.comment       / lex_actions.comment
                + DP.literal       / lex_actions.literal
                + P","          / lex_actions.comma
                + C( DP.gop )      / lex_actions.gop
                + C( DP.sop )      / lex_actions.sop
                + DP.greg_c        / lex_actions.greg
                + C( DP.sreg )     / lex_actions.sreg
                + DP.mref_c         / lex_actions.mref
                + C( DP.variable ) / lex_actions.variable
                + C( DP.label )    / lex_actions.label
                + DP.whitespace
                )^0

-- parse command line

local filename
local handler

local i = 1
while i<=#arg do
        local a = arg[i]
        i = i + 1
        if a == "-h" or a == "--help" then
                print '0x10c'
                print ''
                print ' -h --help                         - this help'
                print ' -v --verbose                      - be more verbose'
                print ' -l --lex <file>                   - run lexer on a file'
                print ' -o --output <file>                - write output here'
                os.exit(0)

        elseif a == "-v" or a == "--verbose" then
                debug_level = debug_level + 1

        elseif a == "-l" or a == "--lex" then
                handler = lexer
                filename = arg[i]
                i = i + 1

        elseif a == "-o" or a == "--output" then
                output = arg[i]
                i = i + 1

        else
                die("unknown option " .. a)
        end
end

if not handler then die("need to specify an action; see --help") end
if not filename then die("need to specify a file") end


-- frontend

local fh = assert(io.open(filename))
local input = fh:read'*a'
fh:close()
local rc = lpeg.match(handler.matcher, input)
if (rc < input:len()) then
        print("ERROR: parser filed here...")
        print(input:sub(rc))
end

handler:dump()
handler:finalize()
handler:output(output)

