#!/usr/bin/lua

require "posix"
local source = debug.getinfo(1).source
local dir = string.match(source, "@(.*)/[^/]*")
if dir then
        local link = posix.readlink(source:match("@(.*)"))
        if link then
                source = dir .. '/' .. link
                dir = string.match(source, "(.*)/[^/]*")
        end
end
if dir then
        package.path = dir .. '/?.lua;' .. package.path
end

local DD = require 'dcpu16.defs'
local DP = require 'dcpu16.parser'
local DA = require 'dcpu16.assembler'
require 'dcpu16.util'

require 'dumper'
local function dump(...)
    print(DataDumper(...))
end


-- parse a file into a parse tree

local function parse_file(program, infile)
        local d = DP.new()

        local res, suc, msg = d:newparse(program, infile or 'stdin')

        if msg then print("\n"..msg.."\n") end
        if not suc then os.exit(1) end

        return res
end

local function assemble(prog)
        local a = DA.new()

        a:append(prog)

        return a
end


------------------------------------------------------------------------

local program
local infile
local outfile
local endian = 'B'
local output_intermediate = false

local long_options = {
        help='h',
        intermediate='i',
        debug='d',
        output='o',
        code='c',
        be='b',
        le='l',
}
long_options['big-endian']='b'
long_options['little-endian']='l'

local option_handlers = {
        h=function(arg,i)
                print("dcpu-asm [options...] [ -c <code> | <infile> ]\n"
                .."\n"
                .." -h --help               - print this help\n"
                .." -d --debug              - turn on debug\n"
                .." -i --intermediate       - output intermediate data\n"
                .." -o --output <bin>       - where to write output\n"
                .." -c --code <code>        - parse this code instead of a file\n"
                .." -l --le --little-endian - generate little endian file\n"
                .." -b --be --big-endian    - generate big endian file (default)\n"
                )
                os.exit(0)
        end,
        d=function(arg,i)
                debug_level = debug_level + 1
                return 0
        end,
        i=function(arg,i)
                output_intermediate = true
                return 0
        end,
        o=function(arg,i)
                outfile = arg[i]
                return 1
        end,
        c=function(arg,i)
                program = arg[i]
                return 1
        end,
        l=function(arg,i)
                endian = 'L'
                return 0
        end,
        b=function(arg,i)
                endian = 'B'
                return 0
        end,
        _=function(arg,i)
                if infile then
                        die"can only specify input file once"
                end
                infile = arg[i]
                return 1
        end
}

parse_args(arg, option_handlers, long_options)


if program == nil and infile ~= nil then
        local f = assert(io.open(infile))
        local program = f:read'*all'
        f:close()
elseif program ~= nil and infile == nil then
        -- we were given a program
        if outfile == nil then
                -- default output file
                outfile = 'dcpu16.out'
        end
else
        die(arg[0].." expecting either a <file> or -c <code>")
end

-- still don't have an output file?  make one up
if outfile == nil then
        local dir, base, ext = split_file_name(infile)

        if base == nil then
                outfile = infile..".out"
        else
                outfile = base..".out"
        end
end

local prog = parse_file(program, infile)
local a = assemble(prog)

if debug_level > 0 then
        a:dump(io.stderr)
end

local f
if outfile == '-' then
        f = io.stdout
else
        io.stderr:write("output going to "..outfile.."\n")
        f = assert(io.open(outfile, "w+"))
end

if output_intermediate then
        a:write_intermediate(f)
else
        a:write(f, endian)
end

